-- MySQL Script generated by MySQL Workbench
-- Thu Jun 12 22:15:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetocontrato
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetocontrato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetocontrato` DEFAULT CHARACTER SET utf8 ;
USE `projetocontrato` ;

-- -----------------------------------------------------
-- Table `projetocontrato`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetocontrato`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomecategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetocontrato`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetocontrato`.`produto` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_categoria_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `projetocontrato`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
