-- MySQL Script generated by MySQL Workbench
-- Sun Jun 15 20:15:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema contratoforn
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema contratoforn
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `contratoforn` DEFAULT CHARACTER SET utf8 ;
USE `contratoforn` ;

-- -----------------------------------------------------
-- Table `contratoforn`.`faturamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contratoforn`.`faturamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prazo` VARCHAR(45) NOT NULL,
  `vencimento` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contratoforn`.`representante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contratoforn`.`representante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contratoforn`.`contratada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contratoforn`.`contratada` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) NOT NULL,
  `razaosocial` VARCHAR(100) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `representante_id` INT NOT NULL,
  UNIQUE INDEX (`cnpj` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_contratada_representante1_idx` (`representante_id` ASC),
  CONSTRAINT `fk_contratada_representante1`
    FOREIGN KEY (`representante_id`)
    REFERENCES `contratoforn`.`representante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contratoforn`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contratoforn`.`contrato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `data` DATE NOT NULL,
  `faturamento_id` INT NOT NULL,
  `contratada_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contrato_faturamento` (`faturamento_id` ASC),
  INDEX `fk_contrato_contratada1_idx` (`contratada_id` ASC),
  CONSTRAINT `fk_contrato_faturamento`
    FOREIGN KEY (`faturamento_id`)
    REFERENCES `contratoforn`.`faturamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_contratada1`
    FOREIGN KEY (`contratada_id`)
    REFERENCES `contratoforn`.`contratada` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contratoforn`.`contratante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contratoforn`.`contratante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) NOT NULL,
  `razaosocial` VARCHAR(100) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `cidade` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `contrato_id` INT NOT NULL,
  `faturamento_id` INT NOT NULL,
  `representante_id` INT NOT NULL,
  UNIQUE INDEX (`cnpj` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_contratante_contrato2_idx` (`contrato_id` ASC),
  INDEX `fk_contratante_faturamento1_idx` (`faturamento_id` ASC),
  INDEX `fk_contratante_representante1_idx` (`representante_id` ASC),
  CONSTRAINT `fk_contratante_contrato2`
    FOREIGN KEY (`contrato_id`)
    REFERENCES `contratoforn`.`contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratante_faturamento1`
    FOREIGN KEY (`faturamento_id`)
    REFERENCES `contratoforn`.`faturamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratante_representante1`
    FOREIGN KEY (`representante_id`)
    REFERENCES `contratoforn`.`representante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contratoforn`.`representante_has_contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contratoforn`.`representante_has_contrato` (
  `representante_id` INT NOT NULL,
  `contrato_id` INT NOT NULL,
  PRIMARY KEY (`representante_id`, `contrato_id`),
  INDEX `fk_representante_has_contrato_contrato1_idx` (`contrato_id` ASC),
  INDEX `fk_representante_has_contrato_representante1_idx` (`representante_id` ASC),
  CONSTRAINT `fk_representante_has_contrato_representante1`
    FOREIGN KEY (`representante_id`)
    REFERENCES `contratoforn`.`representante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_representante_has_contrato_contrato1`
    FOREIGN KEY (`contrato_id`)
    REFERENCES `contratoforn`.`contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
